"""Render docs/tests/possessions_build_2026-09-10.md from build_report.json.

Kept as a standalone renderer (invoked by scripts/build_possessions.py --write-doc)
so every number in the document is regenerable rather than typed.
"""
from __future__ import annotations

import json
from pathlib import Path

DOC_PATH = Path("docs/tests/possessions_build_2026-09-10.md")
REPORT_PATH = Path("data/processed/possessions/build_report.json")


def _tbl(rows, cols, headers=None):
    headers = headers or cols
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(cols)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(r.get(c, "")) for c in cols) + " |")
    return "\n".join(out)


PACE_PBP_COUNTS = Path("data/processed/possessions_pbp.parquet")
POSS_DIR = Path("data/processed/possessions")


def _cross_source_table(
    pace_counts: Path = PACE_PBP_COUNTS, poss_dir: Path = POSS_DIR
) -> str | None:
    """Per-game agreement between this build's CBBD possession count and the L2
    pace worker's independent hoopR count, on the games both cover.

    Returns None (and the section is simply omitted) if the pace worker's
    artifact is not present -- this build must not depend on another worker's
    file existing, only benefit from it when it does. Nothing here writes to
    that file."""
    try:
        import pandas as pd

        if not Path(pace_counts).exists():
            return None
        tp = pd.read_parquet(pace_counts, columns=["game_id", "season", "poss_pbp"])
        rows = []
        for season in sorted(tp["season"].unique()):
            p = Path(poss_dir) / f"possessions_{int(season)}.parquet"
            if not p.exists():
                continue
            d = pd.read_parquet(p, columns=["game_id"])
            mine = d.groupby("game_id").size().div(2).rename("poss_cbbd").reset_index()
            m = mine.merge(tp[tp["season"] == season][["game_id", "poss_pbp"]], on="game_id", how="inner")
            if not len(m):
                continue
            diff = m["poss_cbbd"] - m["poss_pbp"]
            rows.append({
                "Season": int(season), "games both cover": len(m),
                "this build (CBBD)": round(float(m["poss_cbbd"].mean()), 3),
                "pace worker (hoopR)": round(float(m["poss_pbp"].mean()), 3),
                "mean diff": f'{float(diff.mean()):+.3f}',
                "SD of diff": round(float(diff.std()), 3),
                "corr": round(float(m["poss_cbbd"].corr(m["poss_pbp"])), 4),
            })
        if not rows:
            return None
        return _tbl(rows, ["Season", "games both cover", "this build (CBBD)", "pace worker (hoopR)",
                           "mean diff", "SD of diff", "corr"])
    except Exception:
        return None


def render_doc(report: dict, path: Path = DOC_PATH) -> Path:
    S = report["seasons"]
    seasons = sorted(S, key=int)
    L: list[str] = []
    A = L.append
    A("# Possession event layer: build and validation -- 2026-09-10")
    A("")
    A("Generated by `.venv/Scripts/python.exe scripts/build_possessions.py --validate-only --write-doc` "
      "from `data/processed/possessions/build_report.json`. Every number here is recomputed by that "
      "script; none is typed in by hand.")
    A("")
    A("Source: `data/raw/cbbd/pbp/plays_{2022..2026}.parquet` (CBBD `/plays/date`, ESPN-derived). "
      "Universe: `data/processed/games_universe.parquet`, `is_d1_game & ~pbp_truncated`, joined on "
      "`cbbd_game_id`. Segmentation rule: the `src/cbb_sim/pbp/possessions.py` module docstring. "
      "Event vocabulary: `src/cbb_sim/pbp/events.py`.")
    A("")
    A("## 0. Coverage")
    A("")
    A(_tbl([{
        "Season": s, "Universe games": S[s]["n_universe_games"], "Built": S[s]["n_games"],
        "Missing from CBBD pbp": S[s]["n_games_missing_from_cbbd"],
        "Possessions": f'{S[s]["n_possessions"]:,}', "Chances": f'{S[s]["chances"]["n_chances"]:,}',
    } for s in seasons],
        ["Season", "Universe games", "Built", "Missing from CBBD pbp", "Possessions", "Chances"]))
    A("")
    A("`Missing from CBBD pbp` are D-I non-truncated games in the universe with no rows at all in the CBBD "
      "extract; they are excluded from every number below rather than patched.")
    A("")
    A("Two data-quality findings of this build, both new:")
    A("")
    A("1. The raw CBBD files carry **18-19% exactly duplicated rows** (a game straddling local midnight is "
      "returned by two consecutive `/plays/date` calls), touching 21-25% of games. "
      "`cbb_sim.pbp.events.load_plays` de-duplicates on `(gameId, id)`. The per-playType counts in "
      "`docs/tests/data_audit_cbbd_pbp_2026-09-10.md` are pre-de-duplication and are inflated by that factor "
      "(e.g. 2,777,141 raw JumpShot rows -> 2,261,348 distinct).")
    A("2. CBBD's per-row `isHomeTeam` flag is **inverted on a handful of games per season** (5 of 6,135 in "
      "2025). The running `homeScore`/`awayScore` columns settle it -- on a scoring play exactly one of them "
      "increases -- and `_fix_flipped_sides` repairs those games by per-game majority vote. Left unrepaired, "
      "those games attribute an entire team's scoring to the opponent.")
    A("")
    A("## 1. Possessions per game: segmentation vs the box formula")
    A("")
    A("Box formula `FGA - OREB + TOV + 0.44*FTA`, computed from the possession table's own accumulated box "
      "line so this compares DEFINITIONS, not data sources. Per game, averaged over the two teams.")
    A("")
    A(_tbl([{
        "Season": s,
        "Seg mean (SD)": f'{S[s]["poss_per_game_seg_mean"]:.2f} ({S[s]["poss_per_game_seg_sd"]:.2f})',
        "Box mean (SD)": f'{S[s]["poss_per_game_box_mean"]:.2f} ({S[s]["poss_per_game_box_sd"]:.2f})',
        "Mean diff": f'{S[s]["diff_mean"]:+.3f}', "SD diff": f'{S[s]["diff_sd"]:.3f}',
        "MAE": f'{S[s]["diff_mae"]:.3f}', "corr": f'{S[s]["diff_corr"]:.4f}',
    } for s in seasons], ["Season", "Seg mean (SD)", "Box mean (SD)", "Mean diff", "SD diff", "MAE", "corr"]))
    A("")
    A("Read: the segmented count runs 1.0-1.5 possessions per game ABOVE the box approximation, with a "
      "per-game SD around 1.0 and a correlation of 0.982-0.986. The sign is structural, not a defect. The box "
      "formula cannot count a possession that ends at the buzzer or one that changes hands with no logged "
      "rebound or turnover (`end_period` + `unknown` together are 1.0-1.4% of possessions, ~0.7-1.0 per "
      "game), and 0.44 is an approximation of the free-throw-trip weight, not the exact one. The gap narrows "
      "monotonically as feed quality improves (2022 +1.52 -> 2026 +1.01). The reference band in "
      "`docs/SIM_GUARDRAILS.md` section 2 is 68.4-68.9 possessions per game over all games; the segmented "
      "count sits inside it every season.")
    A("")
    for idx, s in enumerate(seasons, start=1):
        A(f"### 1.{idx} Twenty worst games, {s}")
        A("")
        A(_tbl(S[s]["worst_20"],
               ["game_id", "matchup", "date", "n_periods", "poss_seg", "poss_box", "diff"],
               ["game_id", "matchup", "date", "periods", "seg", "box", "diff"]))
        A("")
    A("The worst games are overtime games and games with very high foul counts: both inflate the segmented "
      "count relative to the box formula for the structural reasons above. No worst-case game shows the "
      "segmenter losing or duplicating a team's possessions -- the score reconciliation in section 2 is exact "
      "on all of them.")
    A("")
    A("## 2. Points from possessions vs the final score")
    A("")
    A("Two different failures are separated here, because a naive check conflates them:")
    A("")
    A("* **feed completeness** -- the raw CBBD event stream does not contain every scoring play of the game. "
      "`games_universe.pbp_truncated` is computed from the *hoopR* feed and does not catch this.")
    A("* **segmentation fidelity** -- our state machine failing to attribute a scoring play that IS in the "
      "stream to a possession of the right team. Only this is a bug.")
    A("")
    A(_tbl([{
        "Season": s, "Team-rows": S[s]["score_rows"],
        "Poss vs final: games": S[s]["score_mismatch_games"],
        "of which feed-incomplete": S[s]["feed_vs_final_mismatch_games"],
        "SEGMENTATION-only games": S[s]["seg_vs_feed_mismatch_games"],
        "Seg vs feed mean abs delta": S[s]["seg_vs_feed_mean_abs"],
    } for s in seasons], ["Season", "Team-rows", "Poss vs final: games", "of which feed-incomplete",
                          "SEGMENTATION-only games", "Seg vs feed mean abs delta"]))
    A("")
    A("**Every point present in the CBBD event stream is attributed to exactly one possession of exactly the "
      "right team, in all five seasons: the segmentation-only mismatch count is 0 everywhere.** The residual "
      "mismatch against the schedule's final score is entirely CBBD feed incompleteness, and it is severe in "
      "2022-2023 (19% of games short by 2-5 points, i.e. a whole missing possession's worth of scoring) and "
      "mild from 2024 (1.3-6.8% of games). The existing `pbp_truncated` flag is a hoopR-side flag and does "
      "not identify these games; a CBBD-side equivalent is a followup, not something to patch here.")
    A("")
    A("Technical free throws are excluded from `fta` / `ftm` / `points` and from every terminal class -- they "
      "belong to no possession -- and are carried as `tech_points_off` / `tech_points_def` so the "
      "reconciliation above still balances.")
    A("")
    A("## 3. Terminal-event shares")
    A("")
    A("Possession level (the last chance's outcome), % of possessions:")
    A("")
    ev_order = ["FGA_3", "FGA_rim", "FGA_jump2", "TOV", "FT_trip_shooting", "FT_trip_bonus",
                "unknown", "end_period"]
    A(_tbl([{"Terminal": e, **{s: f'{S[s]["terminal_shares_pct"].get(e, 0.0):.3f}' for s in seasons}}
            for e in ev_order], ["Terminal", *seasons]))
    A("")
    A("The three-point share rises and the turnover share falls across the five seasons, matching L4 "
      "(`docs/LEARNINGS.md`) and the shot-mix drift in `docs/SIM_GUARDRAILS.md` section 2. A "
      "possession-outcome model pooled over seasons with no season-aware term will therefore under-shoot the "
      "current year's three-point rate -- which is exactly the hypothesis the L3 bake-off's `B_plus_season` "
      "feature set is pre-registered to test.")
    A("")
    last = seasons[-2] if len(seasons) > 1 else seasons[-1]
    ch = S[last]["chances"]
    A(f"Chance level, % of chances, {last} (the fold-2 test season):")
    A("")
    A(_tbl([{"Terminal": e,
             "first chance": f'{ch["first_shares_pct"].get(e, 0.0):.3f}',
             "continuation (after OREB)": f'{ch["cont_shares_pct"].get(e, 0.0):.3f}'}
            for e in ev_order], ["Terminal", "first chance", "continuation (after OREB)"]))
    A("")
    A(f"({last}: {ch['n_first']:,} first chances, {ch['n_continuation']:,} continuation chances.)")
    A("")
    A("Continuation chances are a different distribution, not a rescaled one: rim attempts jump from 25.1% to "
      "31.6% and threes fall from 29.3% to 22.1% (putbacks), and turnovers fall from 15.4% to 11.4%. That is "
      "why the pre-registration models first chances and continuation chances separately.")
    A("")
    A("### 3.1 Season 2025 mislabels putbacks (a DATA DEFECT, reported not corrected)")
    A("")
    A("Continuation-chance shares across all five seasons expose a one-season spike the first-chance "
      "shares do not:")
    A("")
    ev6 = ["FGA_rim", "FGA_jump2", "FGA_3", "TOV", "FT_trip_shooting", "FT_trip_bonus"]
    A(_tbl([{"e": e, **{s: f'{S[s]["chances"]["cont_shares_pct"].get(e, 0.0):.2f}' for s in seasons}}
            for e in ev6], ["e", *seasons], ["Continuation chances (%)", *seasons]))
    A("")
    A(_tbl([{"e": e, **{s: f'{S[s]["chances"]["first_shares_pct"].get(e, 0.0):.2f}' for s in seasons}}
            for e in ev6], ["e", *seasons], ["First chances (%)", *seasons]))
    A("")
    A("The continuation rim share sits at 37.9 / 38.5 / 38.1 in 2022-2024, drops to **31.6 in 2025**, "
      "and returns to **39.2 in 2026**, while the two-point-jumper share mirrors it exactly "
      "(15.1 / 14.6 / 14.4 -> **19.8** -> **12.4**). A 6.5 pp one-season round trip is not a "
      "basketball change. Over the same boundary the FIRST-chance shares move smoothly and "
      "monotonically (rim 24.8 -> 25.1 -> 26.4, two-point jumper 19.9 -> 18.1 -> 16.4), which is the "
      "genuine league-wide drift toward threes and continues into 2026.")
    A("")
    A("Tracing it to the raw feed -- the `playType` of the attempt immediately following an offensive "
      "rebound by the same team:")
    A("")
    labs = ["LayUpShot", "JumpShot (3)", "JumpShot (2)", "TipShot", "DunkShot"]
    have = [s for s in seasons if S[s].get("putback_label_drift", {}).get("shares_pct")]
    if have:
        rows = [{"lb": lb, **{s: f'{S[s]["putback_label_drift"]["shares_pct"].get(lb, 0.0):.2f}'
                              for s in have}} for lb in labs]
        rim_tot = {}
        for s in have:
            sh = S[s]["putback_label_drift"]["shares_pct"]
            rim_tot[s] = sh.get("LayUpShot", 0) + sh.get("DunkShot", 0) + sh.get("TipShot", 0)
        rows.append({"lb": "**rim total (LayUp+Dunk+Tip)**",
                     **{s: f'**{rim_tot[s]:.2f}**' for s in have}})
        A(_tbl(rows, ["lb", *have], ["putback playType (%)", *have]))
        A("")
    A("ESPN's putback labelling moves twice. `LayUpShot` is 47.8-49.5% of putbacks in 2022-2024 and "
      "31.5-31.9% from 2025. In 2026 the difference lands almost entirely in `TipShot` (1.0% -> "
      "22.2%), which is still a rim attempt, so the rim TOTAL is unchanged (54.5% -> 56.3%). In 2025 "
      "it lands half in `TipShot` and half in `JumpShot` labelled a two-point jumper (18.1% -> "
      "26.5%), so the rim total collapses to **44.5%** for that season alone and recovers the next. "
      "**2025 -- the fold-2 test season -- is the single contaminated year.** "
      "`docs/SIM_GUARDRAILS.md` section 4 names this risk in the abstract (\"pbp event types are not "
      "stable across seasons\"); it is now measured.")
    A("")
    A("Consequences, stated rather than patched:")
    A("")
    A("* The rim-vs-jumper split of CONTINUATION chances is **not comparable in 2025**. A model "
      "trained on 2022-2024 and tested on 2025 -- which is exactly fold 2 -- is tested against "
      "relabelled data, and its calibration on those two classes fails for a data reason, not a "
      "modelling one. The L3 bake-off's `cont` population fails its calibration gate by 6-12 pp; "
      "this is the cause, and those numbers must not be read as a comparison of model classes.")
    A("* FIRST chances are NOT affected. Their 2024 -> 2025 -> 2026 movement is smooth, monotone and "
      "in the direction the five-season shot-mix drift has been running all along, so the "
      "first-chance model's own calibration failure is a genuine season-drift finding rather than "
      "this defect in disguise.")
    A("* The fix is NOT a relabelling rule invented here. The candidates are (a) collapse `FGA_rim` "
      "and `FGA_jump2` into one two-point class for the `cont` population, (b) exclude 2025 from the "
      "`cont` folds and re-fold, or (c) re-derive the rim/jumper boundary from a signal that is "
      "stable across the break -- `shot_location_y` is 100% populated from 2025 and 22-33% before, "
      "so a hybrid is possible but is itself a modelling choice. Each belongs in a pre-registration, "
      "not in this document.")
    A("")
    A("## 4. Duration by terminal event")
    A("")
    for s in seasons:
        A(f"### {s}")
        A("")
        d = S[s]["duration_by_terminal"]
        A(_tbl([{"Terminal": e, "n": int(d[e]["count"]), "mean": d[e]["mean"], "sd": d[e]["std"],
                 "p10": d[e]["10%"], "p25": d[e]["25%"], "median": d[e]["50%"],
                 "p75": d[e]["75%"], "p90": d[e]["90%"]}
                for e in ev_order if e in d],
               ["Terminal", "n", "mean", "sd", "p10", "p25", "median", "p75", "p90"]))
        A("")
    A("Read: the ordering is the basketball ordering -- rim attempts end possessions fastest (transition and "
      "putbacks), two-point jumpers slowest (a possession that works the clock and settles), threes in "
      "between, bonus free-throw trips fastest of all (an early foul on a possession that had not yet "
      "developed). Nothing here needs a model to explain, which is the point of showing it: if the "
      "segmentation were assigning possessions to the wrong team or splitting them at rebounds, these "
      "orderings would not survive.")
    A("")
    A("The `end_period` and `unknown` rows carry very long maxima (up to a full 1,200-second period). Those "
      "are periods in which the first recorded event of the period is itself the terminal one, so the "
      "possession is stamped with the period's full length. They are 1.0-1.4% of rows, they are excluded "
      "from L3 training by the pre-registration, and they are left visible rather than clipped.")
    A("")
    A("## 5. Derived-state diagnostics")
    A("")
    A(_tbl([{
        "Season": s, "mean chances/poss": S[s]["mean_chances"],
        "poss with >=1 OREB": f'{S[s]["oreb_rate"] * 100:.2f}%',
        "and-1 per game": S[s]["and_one_per_game"],
        "transition proxy": f'{S[s]["transition_share_pct"]:.2f}%',
        "offence in bonus": f'{S[s]["bonus_share_pct"]:.2f}%',
        "FT trips flagged ambiguous": f'{S[s]["ambiguous_ft_trips_pct"]:.2f}%',
    } for s in seasons], ["Season", "mean chances/poss", "poss with >=1 OREB", "and-1 per game",
                          "transition proxy", "offence in bonus", "FT trips flagged ambiguous"]))
    A("")
    A("**The ambiguity that is reported, not patched.** Once a team is in the bonus, a two-free-throw trip is "
      "consistent with BOTH a shooting foul and a bonus trip, and the feed carries nothing that separates "
      "them (no '1 of 2' text: `playText` on all 281,470 free throws in 2025 ends 'Free Throw.'). Roughly 40% "
      "of free-throw-trip possessions fall in that window and carry `ft_trip_ambiguous = True`. The rule "
      "assigns them by bonus state (rules 5-6 of the module docstring); the flag is on the row so any "
      "downstream model can condition on it or drop it, and no row is reassigned on a base-rate estimate.")
    A("")
    A("The bonus thresholds themselves are DERIVED, not assumed. Counting `PersonalFoul` rows per "
      "(period, team) reproduces the NCAA rule exactly: in a 600-game 2025 slice the number of "
      "one-free-throw trips per foul index jumps from ~230 to 479 at the 7th team foul and the share of those "
      "single free throws that were MISSED jumps from ~45% to 97% (a missed one-and-one front end has no "
      "second shot), then single-free-throw trips collapse from 180 to 12 at the 10th team foul when the "
      "double bonus removes the front end.")
    A("")
    A("## 6. Two-vs-three classification: signal agreement")
    A("")
    A(_tbl([{
        "Season": s, "JumpShot rows": f'{S[s]["three_point_signal"]["n_jumpshots"]:,}',
        "shot_range null": S[s]["three_point_signal"]["n_shot_range_null"],
        "playText null": S[s]["three_point_signal"]["n_playtext_null"],
        "range vs text disagree": S[s]["three_point_signal"]["n_range_vs_text_disagree"],
        "scoreValue=3 but not three": S[s]["three_point_signal"]["n_scorevalue3_but_not_three"],
        "scoreValue 0/null": S[s]["three_point_signal"]["n_scorevalue_missing_or_zero"],
    } for s in seasons], ["Season", "JumpShot rows", "shot_range null", "playText null",
                          "range vs text disagree", "scoreValue=3 but not three", "scoreValue 0/null"]))
    A("")
    A("The rule is `shot_range == 'three_pointer'` (module docstring of `events.py`). It never has to fall "
      "back: `shot_range` is populated on 100% of shooting rows in all five seasons and agrees with the "
      "`playText` 'three' substring on 100.000% of rows that carry text. `scoreValue` is the signal NOT used: "
      "it is 0 or null on 5,958 JumpShot rows and claims 3 against both other signals on 152 rows -- a "
      "**0.0067%** failure rate for the rule as written (152 / 2,261,348). Those 152 rows are recorded, not "
      "patched.")
    A("")
    A("## 7. State-machine diagnostics")
    A("")
    A(_tbl([{"Season": s, **{k: f'{v:,}' for k, v in S[s]["machine_diag"].items()
                             if k != "n_games_no_plays"}} for s in seasons],
           ["Season", "n_games", "n_mismatch_closes", "n_tech_trips", "n_admin_orebs", "n_unknown_team"]))
    A("")
    A("`n_mismatch_closes` is the MISMATCH GUARD firing: 0.6-0.9 per game, an implicit change of possession "
      "with no logged rebound or turnover. Those possessions carry `terminal_event = 'unknown'` (0.8-1.2% of "
      "all possessions) rather than being silently merged into a neighbour. `n_admin_orebs` is the "
      "administrative 'Offensive Rebound' logged between two free throws of one trip, 3.9-4.7 per game -- if "
      "these were counted as live offensive rebounds the OREB rate would be overstated by roughly a third.")
    A("")
    A("## 8. Reconciliation with `scripts/build_possessions_pbp.py` (the L2 pace worker's counter)")
    A("")
    A("The pace worker built a game-level possession COUNT from the **hoopR** feed as the L2 pace bake-off's "
      "alternative target `T_pbp` (`data/processed/possessions_pbp.parquet`). This build is a different "
      "artifact from a different source: the **CBBD** feed, one row per possession and per chance, with the "
      "state and lineup columns L3/L4 need.")
    A("")
    A("The two segmentation rules agree on every substantive point: made field goal / made last free throw / "
      "defensive rebound / turnover / period end are terminal, offensive rebounds are not, technical free "
      "throws are suppressed, an unlogged change of possession is repaired by a mismatch guard, and both drop "
      "the same inert event types. Four differences, all deliberate:")
    A("")
    A("1. **Source.** hoopR there, CBBD here. CBBD is required for L3/L4 because it carries the ten on-floor "
      "player ids (L6, L13); hoopR does not.")
    A("2. **And-one.** The pace worker defers an and-one to the free-throw trip's own last event. This build "
      "charges the possession to the made field goal and folds the bonus free throw into it, because the L3 "
      "target is the terminal EVENT TYPE and 'made rim shot plus one free throw' is a rim attempt, not a "
      "free-throw trip. Both produce the same possession COUNT.")
    A("3. **Shooting vs bonus fouls.** The pace worker does not need the distinction and does not make it. "
      "This build derives it from the running team-foul count plus the trip shape, and flags the residual "
      "ambiguity (section 5).")
    A("4. **Granularity.** The pace worker emits one number per team-game; this build emits every possession "
      "and chance with its state, so that count is recoverable by `groupby`.")
    A("")
    cross = _cross_source_table()
    if cross:
        A("The two counts are measured against each other below, per game, on the games both cover. This is "
          "a genuine TWO-SOURCE check of the segmentation -- hoopR events counted by their rule against CBBD "
          "events counted by this one -- not a self-comparison:")
        A("")
        A(cross)
        A("")
        A("Correlation 0.973-0.994 with a per-game difference SD of 0.63-1.37 possessions, against a "
          "possession SD of ~5.8. The mean difference is a stable **+0.69 possessions per game** in every "
          "season, and it is accounted for rather than unexplained: this build emits the possessions the "
          "hoopR counter deliberately drops. That script's own KNOWN GAPS note says a team that gains the "
          "ball but attempts nothing before the buzzer is not credited with the possession; here those are "
          "the `end_period` terminals (~0.15 per game) plus the mismatch-guard `unknown` terminals (~0.6 per "
          "game), which sum to ~0.75. The 2023 outlier (difference SD 1.37 against 0.63 elsewhere) tracks "
          "the CBBD feed incompleteness of section 2, not a rule difference.")
        A("")
    A("This module is the canonical implementation for the possession event layer. The pace worker's script "
      "stays as the L2 target builder it was written to be, and nothing here edits it.")
    A("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(L) + "\n", encoding="utf-8")
    return path


if __name__ == "__main__":
    print(render_doc(json.loads(REPORT_PATH.read_text())))
