"""Tests for cbb_sim.team_rate_adapter on REAL sub-model design frames. A sample of the served designs is
substituted with the E3 table, with fold F2 (seasons 2022-2025).

The tests skip when the local data files are absent: the E3 tables are regenerated by
scripts/exp_team_rate_estimator_v3.py / _v4.py.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from cbb_sim import team_rate_adapter as TRA

T1 = Path("data/processed/team_rate_features_E3_v1.parquet")
T2 = Path("data/processed/team_rate_features_E3_v2.parquet")
PO = Path("data/processed/models/possession_outcome/round2/design.parquet")
FG = Path("data/processed/models/fg_make/design_v2_shotshooter.parquet")
RB = Path("data/processed/models/rebound/round3/design_round3.parquet")


def _sample(path, cols, n=40000, seed=0):
    d = pd.read_parquet(path, columns=cols)
    return d.sample(n=min(n, len(d)), random_state=seed).sort_index()


def _check(before, after, replaced):
    assert len(before) == len(after) and before.index.equals(after.index)
    untouched = [c for c in before.columns if c not in replaced and not c.startswith("x_")]
    pd.testing.assert_frame_equal(before[untouched], after[untouched])
    for c in replaced:
        assert not after[c].isna().any()
        # same construct: substituted values track the served ones (both are as-of team rates)
        assert np.corrcoef(before[c], after[c])[0, 1] > 0.5, c


@pytest.mark.skipif(not (FG.exists() and T1.exists()), reason="local data absent")
def test_fg_make_real_frame():
    f = _sample(FG, ["season", "game_id", "off_team_id", "def_team_id", "shot_class", "off_make_c", "def_allow_c",
                     "shooter_make_c"])
    f = f[f["season"] >= 2023]                      # 2022 as-of rates start from zero in both sources
    out = TRA.apply(f, T1, "fg_make", fold="F2", missing="keep_served")
    _check(f, out, ["off_make_c", "def_allow_c"])
    assert out.attrs["team_rate_adapter"]["rows_kept_served"] < 0.002 * len(f)


@pytest.mark.skipif(not (RB.exists() and T1.exists()), reason="local data absent")
def test_rebound_real_frame_and_sign():
    f = _sample(RB, ["season", "game_id", "off_team_id", "def_team_id", "off_oreb_c", "opp_def_dreb_c",
                     "off_rating_off_c"])
    f = f[f["season"] >= 2023]
    out = TRA.apply(f, T1, "rebound", fold="F2", missing="keep_served")
    _check(f, out, ["off_oreb_c", "opp_def_dreb_c"])


@pytest.mark.skipif(not (PO.exists() and T2.exists()), reason="local data absent")
def test_possession_outcome_real_frame_with_interactions():
    cols = ["season", "game_id", "offense_team_id", "defense_team_id", "off_3pa_c", "off_rim_c", "off_tov_c",
            "off_ftr_c", "opp_def_3pa_c", "opp_def_rim_c", "opp_def_tov_c", "opp_def_ftr_c",
            "x_off_tov_c__opp_def_tov_c", "x_off_rating_off_c__def_rating_def_c", "off_rating_off_c"]
    f = _sample(PO, cols)
    f = f[f["season"] >= 2023]
    out = TRA.apply(f, T2, "possession_outcome", fold="F2", missing="keep_served")
    rep = [c for c in TRA.PO_MAP if c in f.columns]
    _check(f, out, rep)
    np.testing.assert_allclose(out["x_off_tov_c__opp_def_tov_c"], out["off_tov_c"] * out["opp_def_tov_c"], rtol=1e-5)
    pd.testing.assert_series_equal(f["x_off_rating_off_c__def_rating_def_c"], out["x_off_rating_off_c__def_rating_def_c"])


@pytest.mark.skipif(not (PO.exists() and T1.exists()), reason="local data absent")
def test_possession_outcome_refuses_v1_table():
    f = _sample(PO, ["season", "game_id", "offense_team_id", "defense_team_id", "off_3pa_c", "off_tov_c"], n=100)
    with pytest.raises(KeyError):
        TRA.apply(f, T1, "possession_outcome", fold="F2")


@pytest.mark.skipif(not (RB.exists() and T1.exists()), reason="local data absent")
def test_missing_key_raises_by_default():
    f = _sample(RB, ["season", "game_id", "off_team_id", "def_team_id", "off_oreb_c", "opp_def_dreb_c"], n=200)
    f.loc[f.index[0], "game_id"] = -1
    with pytest.raises(AssertionError):
        TRA.apply(f, T1, "rebound", fold="F2")
