#!/usr/bin/env bash
# local: fetch one arm's outputs from the box into results/, then write its gate doc. fetch_doc.sh <ARM> "<title>" "<extra>"
set -uo pipefail
S="$(dirname "$0")"; ARM="$1"; TITLE="$2"; EXTRA="$3"
cd /c/Users/devuser/CBB-clean-sheet
IP=$(cat $S/ip.txt); K="-i /c/Users/devuser/.ssh/cfb-sweep-ohio.pem -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"
RT="v3full_${ARM}_s200_o0"
mkdir -p results/engine_v0/v3full_grade "results/engine_v0/$RT"
scp -q $K "ec2-user@$IP:cbb/results/engine_v0/v3full_grade/*.md" "ec2-user@$IP:cbb/results/engine_v0/v3full_grade/*.json" results/engine_v0/v3full_grade/
scp -q $K "ec2-user@$IP:cbb/results/engine_v0/$RT/games.parquet" "ec2-user@$IP:cbb/results/engine_v0/$RT/run_meta.json" "results/engine_v0/$RT/"
export PYTHONIOENCODING=utf-8
OUT="docs/tests/engine_gates_F2_2025_s200_v3_${ARM}_full_2026-09-30.md"
.venv/Scripts/python.exe scripts/ops_v3_gate_doc_v1.py --dir results/engine_v0/v3full_grade --arm "$RT" --title "$TITLE" --out "$OUT" \
  --ref v3full_S0_s200_o0 --floors v3full_S0f1_s200_o1000,v3full_S0f2_s200_o2000,v3full_S0f3_s200_o3000,v3full_S0f4_s200_o4000 --labels "$ARM" --extra "$EXTRA"
{ echo; echo "## Decision 12 floors: paired game bootstrap + four seed-offset draws (verified truth), G5 by component, TOV on the count"; echo;
  echo "Generated by \`scripts/ops_pair_bootstrap_v1.py\` on the box (\`results/engine_v0/v3full_grade/${RT}__boot.json\`). This table is the one the Decision 12 reading uses: floor = max(2 x SD over the five S0 draws, half-width of the paired game-bootstrap 95% CI)."; echo;
  cat "results/engine_v0/v3full_grade/${RT}__boot.md"; } >> "$OUT"
echo "wrote $OUT"
