"""ops_v3_gate_doc_v1.py -- operator 2026-09-30. Writes one gate-table doc for an arm: headline G1-G9 lines under verified truth and
current truth side by side (values and statuses), the per-gate overall verdicts, and, when --ref is given, the paired table against
the reference with the multi-draw floor under BOTH truths (ops_v3_pair_table_v1.py). Parses eval_gates.py md; recomputes nothing.

    python scripts/ops_v3_gate_doc_v1.py --dir <md dir> --arm <tag> --title "..." --out docs/tests/<file>.md \
        [--ref <tag> --floors <tag,tag,...>] [--extra "free text paragraph"]
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import diag_pair_gate_reports as D  # noqa: E402

ap = argparse.ArgumentParser()
ap.add_argument("--dir", required=True)
ap.add_argument("--arm", required=True)
ap.add_argument("--title", required=True)
ap.add_argument("--out", required=True)
ap.add_argument("--ref", default="")
ap.add_argument("--floors", default="")
ap.add_argument("--labels", default="")
ap.add_argument("--extra", default="")
a = ap.parse_args()
d = Path(a.dir)
V, C = D.parse(d / f"{a.arm}__verified.md"), D.parse(d / f"{a.arm}__current.md")
gv = lambda p: next((l for l in p.read_text(encoding="utf-8").splitlines() if l.startswith("Games graded")), "")
L = [f"# {a.title}\n", a.extra + "\n" if a.extra else "",
     f"Arm run `{a.arm}`. Generated by `scripts/ops_v3_gate_doc_v1.py` from `scripts/eval_gates.py` reports (nothing recomputed). "
     "Verified truth = `CBB_TRUTH=verified_v1` (5,705 games in the full read; unplayed/forfeit finals dropped); current = today's default truth. "
     "Label: absolute G5/G9 lines on verified truth are not comparable with pre-flip reports.\n",
     f"- verified: {gv(d / (a.arm + '__verified.md'))[:150]}", f"- current: {gv(d / (a.arm + '__current.md'))[:150]}\n",
     "## Headline lines, verified vs current truth\n",
     "| gate | line | target | value (verified) | status | value (current) | status |", "|---|---|---|---|---|---|---|"]
for k, r in V["rows"].items():
    c = C["rows"].get(k, {"value": "n/a", "status": "n/a"})
    L.append(f"| {k[0]} | {k[1]} | {r['target']} | {r['value']} | {r['status']} | {c['value']} | {c['status']} |")
L += ["", "## Per-gate overall verdict\n", "| gate | verified | current |", "|---|---|---|"]
for g in sorted(V["overall"]):
    L.append(f"| {g} | {V['overall'][g]} | {C['overall'].get(g, 'n/a')} |")
if a.ref:
    for t in ("verified", "current"):
        with tempfile.NamedTemporaryFile(suffix=".md", delete=False) as tf:
            name = tf.name
        cmd = [sys.executable, str(Path(__file__).resolve().parent / "ops_v3_pair_table_v1.py"), "--dir", a.dir, "--truth", t, "--ref", a.ref,
               "--floors", a.floors, "--arms", a.arm, "--labels", a.labels or a.arm, "--out", name]
        subprocess.run(cmd, check=True, capture_output=True)
        L += ["", Path(name).read_text(encoding="utf-8").replace("# Paired gate table", "## Paired table", 1)]
if a.floors and not a.ref:
    import statistics as st
    fl = [t for t in a.floors.split(",") if t]
    for t in ("verified", "current"):
        ps = [D.parse(d / f"{x}__{t}.md") for x in [a.arm] + fl]
        L += ["", f"## Seed-offset floor draws of this arm ({t} truth): draw 0 = {a.arm}, draws 1-{len(fl)} = reruns on other seeds", "",
              "| gate | line | " + " | ".join(f"draw {i}" for i in range(len(fl) + 1)) + " | SD over draws |",
              "|---|---|" + "---|" * (len(fl) + 2)]
        for k in ps[0]["rows"]:
            vals = [D.first_num(p_["rows"][k]["value"]) if k in p_["rows"] else None for p_ in ps]
            xs = [x for x in vals if x is not None]
            if vals[0] is None or len(xs) < 2:
                continue
            L.append(f"| {k[0]} | {k[1]} | " + " | ".join("n/a" if x is None else f"{x:.6g}" for x in vals) + f" | {st.stdev(xs):.4g} |")
Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8")
print("wrote", a.out)
